---
interfaces:
    ge-0/0/0: 
      ip: "10.3.0.3/31"
      area: "0.0.0.0"
      type: "p2p"
      metric: "100"
    ge-0/0/1: 
      ip: "10.3.0.4/31"
      area: "0.0.0.0"
      type: "p2p"
      metric: "100"
    ge-0/0/2:
      ip: "10.2.0.2/24"
      area: "0.0.0.0"
      type: "p2p"
      metric: "100"
router_id: "3.3.3.3"
